bot.token: NzI0MjMzMDgwNDQ0ODEzMzUy.GGGwCe.7UhGc3ib-3yy5lUeDA_vvD5LqB1oooJOWOOa2Q
bot.prefix: '!'
bot.owner: 216936486875037699
bot.status: ManageTheDiscord
bot.url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
channel.join: 972125539177492571
channel.leave: 972125539177492571
